// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacrMeetPlanner.Models;

namespace SacrMeetPlanner.Migrations
{
    [DbContext(typeof(SacrMeetPlannerContext))]
    partial class SacrMeetPlannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacrMeetPlanner.Models.Meeting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Announcements");

                    b.Property<string>("Conducting");

                    b.Property<DateTime>("Date");

                    b.Property<int>("FirstHimnNum");

                    b.Property<string>("FirstHimnTitle");

                    b.Property<string>("FirstPrayer");

                    b.Property<string>("FirstSpeaker");

                    b.Property<int>("LastHimnNum");

                    b.Property<string>("LastHimnTitle");

                    b.Property<string>("LastPrayer");

                    b.Property<string>("Presiding");

                    b.Property<int>("SecondHimnNum");

                    b.Property<string>("SecondHimnTitle");

                    b.Property<string>("SecondSpeaker");

                    b.Property<string>("Subject");

                    b.Property<string>("ThirdSpeaker");

                    b.HasKey("ID");

                    b.ToTable("Meeting");
                });
#pragma warning restore 612, 618
        }
    }
}
